### ISSUE TITLE
Unable to use systemctl in litmusimage/ubuntu:16.04 

### ISSUE THREAD

**Issue by heytrav** [puppetlabs/litmusimage#35]
## Describe the Bug
In the `litmusimage/ubuntu:16.04` image it is not possible to manage processes using `systemctl `.  It works fine with `litmusimage/18.04` and `litmusimage/20.04`.

When using `systemctl` to start or check the status of a process I get the following output:
```
root@xenial:/# systemctl status sshd
Failed to connect to bus: No such file or direct
```

## Expected Behavior
When I run a command like the following
```
systemctl start sshd
```
I expect to start the `sshd` daemon.

or 
```
systemctl status sshd
```
I expect output from systemd about the status of the `sshd` daemon.

## Steps to Reproduce
I am running this in Molecule (Ansible test framework) and its here that I am encountering issues. Due to security issues I have to run containers in `unprivileged` mode. The other images work fine.

1. Use `litmusimage/ubuntu:16.04` image in molecule.yml
2. Run molecule to test an ansible role which installs package and attempts to start and stop using: 
    ```
    - name: Start app
      systemd:
         name: myapp
         state: started

    - name: Stop app
      systemd:
         name: myapp
         state: stopped
    ```

Result:
```
TASK [myrolel : Stopping myapp] ************************************
skipping: [trusty]
ok: [focal]
ok: [bionic]
fatal: [xenial]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}

```

## Environment
 - litmusimage/ubuntu:16.04
 - Platform [e.g. Ubuntu 18.04]

## Additional Context
the `./molecule.yml`:

```
---
default_platform: &platform
  privileged: false
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tty: true
  environment:
    container: docker
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bionic
    image: litmusimage/ubuntu:18.04
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    command: /lib/systemd/systemd
    <<: *platform
  - name: focal
    image: litmusimage/ubuntu:20.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    <<: *platform
  - name: xenial
    image: litmusimage/ubuntu:16.04
    tmpfs:
      - /tmp
      - /run
    command: /lib/systemd/systemd
    <<: *platform
provisioner:
  name: ansible
verifier:
  name: ansible

```
